name: Pylint Check

on:
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Get modified Python files
        id: modified_files
        run: |
          git fetch origin main
          git diff --name-only HEAD origin/main > modified_files.txt || echo "" > modified_files.txt
          $modifiedFiles = Get-Content modified_files.txt | Where-Object { $_ -ne "" }
          if ($modifiedFiles) {
            $modifiedFilesString = $modifiedFiles -join ' '
            echo "MODIFIED_FILES=$modifiedFilesString" >> $GITHUB_ENV
          } else {
            echo "No modified files."
          }

      - name: Check MODIFIED_FILES
        run: |
          echo $env:MODIFIED_FILES

      - name: Run Pylint on modified files
        shell: pwsh
        run: |
          if ($env:MODIFIED_FILES -ne "") {
            pylint $env:MODIFIED_FILES
          } else {
            Write-Host "No Python files to check."
            exit 0  # 成功退出
          }
