name: Pylint Check

on:
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Get modified Python files
        id: modified_files
        run: |
          git fetch origin main
          echo "::set-output name=files::$(git diff --name-only origin/main...HEAD | findstr /R "\.py$")"

      - name: Run Pylint on modified files
        run: |
          if [ -n "${{ steps.modified_files.outputs.files }}" ]; then
            pylint ${{ steps.modified_files.outputs.files }}
          else
            echo "No Python files to check."
          fi
