name: Pylint Check

on:
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Check all Python files
        run: |
          $pyFiles = Get-ChildItem -Recurse -Filter "*.py"
          if ($pyFiles.Count -gt 0) {
            pylint $pyFiles.FullName
          } else {
            Write-Host "No Python files to check."
            exit 0
          }
