name: Pylint Check

on:
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Get modified Python files
        id: modified_files
        run: |
          git fetch origin main
          git diff --name-only HEAD origin/main > modified_files.txt || echo "" > modified_files.txt
          set MODIFIED_FILES=
          for /F "delims=" %i in (modified_files.txt) do (
            set MODIFIED_FILES=%MODIFIED_FILES% %i
          )
          echo MODIFIED_FILES=%MODIFIED_FILES% >> $GITHUB_ENV

      - name: Check MODIFIED_FILES
        run: |
          echo %MODIFIED_FILES%

      - name: Run Pylint on modified files
        run: |
          if not "%MODIFIED_FILES%"=="" (
            pylint %MODIFIED_FILES%
          ) else (
            echo No Python files to check.
          )
