name: Pylint Check

on:
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Get modified Python files
        id: modified_files
        run: |
          git fetch origin main
          git diff --name-only HEAD origin/main > modified_files.txt || echo "" > modified_files.txt
          echo "MODIFIED_FILES<<EOF" >> $GITHUB_ENV
          type modified_files.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run Pylint on modified files
        run: |
          if [ -n "${{ env.MODIFIED_FILES }}" ]; then
            pylint ${{ env.MODIFIED_FILES }}
          else
            echo "No Python files to check."
          fi
